server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zjzshb/hubbbs/blob/master/api/yml/
  rabBooleanmq:
    host: 39.108.161.154
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh